branches:
  only:
    - master

platform:
  - x64
configuration:
  - Release
image:
  - Visual Studio 2017
install:
  - vcpkg install hdf5

build_script:
  - mkdir build
  - cd build
  - cmake -G "%generator%" -T "%toolset%"  -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build . --config Release --target doctests
