language: cpp
notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libhdf5-dev
  homebrew:
    packages:
      - hdf5

matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang
      osx_image: xcode11

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        export PATH="$(brew --prefix llvm)/bin:$PATH";
        echo $PATH;
    fi
  - mkdir build && cd build && cmake ..
script:
  - make VERBOSE=1
  - test/doctests -s
