language: cpp
notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libhdf5-dev
  homebrew:
    packages:
      - hdf5

matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11
      compiler: gcc
  allow_failures:
    - os: osx

install:
  - mkdir build && cd build && cmake ..
script:
  - make VERBOSE=1
  - test/doctests -s
