language: cpp
notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libhdf5-dev
      - g++-8
  homebrew:
    packages:
      - hdf5

matrix:
  include:
    - os: linux
      dist: bionic
      env:
        - CXX=g++-8
        - CC=gcc-8
    - os: osx
      osx_image: xcode11


install: mkdir build && cd build && cmake ..
script:
  - make
  - test/doctests -s
